=== bartoszm/snmp123/resources/uk/co/westhawk/test/test.dtd
<!-- /*
 * NAME
 *      $RCSfile: test.dtd,v $
 * DESCRIPTION
 *      [given below]
 * DELTA
 *      $Revision: 1.5 $
 *      $Author: birgita $
 * CREATED
 *      $Date: 2009/03/05 12:59:50 $
 * COPYRIGHT
 *      Westhawk Ltd
 * TO DO
 *
 */ -->

<!-- all tests -->
<!ELEMENT tests (test*)>

<!-- one test -->
<!ELEMENT test (version, host, port, bind, socket_type, (community | usm), request*, result?)>

<!-- test elements -->
<!ELEMENT version EMPTY>
  <!ATTLIST version no (1 | 2c | 3) "1">
<!ELEMENT host (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT bind (#PCDATA)>
<!ELEMENT socket_type EMPTY>
  <!ATTLIST socket_type type (STD | NET | TCP) "STD">

<!ELEMENT community (#PCDATA)>


<!-- usm elements -->
<!ELEMENT usm (username, context, auth, priv?)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT context (id, name)>
<!ELEMENT id (#PCDATA)> 
<!ELEMENT name (#PCDATA)> 

<!ELEMENT auth (aproto, apassw)?>
<!ATTLIST auth ado (yes | no) "no">

<!-- MD5 or SHA1 -->
<!ELEMENT aproto (#PCDATA)>
<!ELEMENT apassw (#PCDATA)> 

<!ELEMENT priv (pproto, ppassw?)>
<!ATTLIST priv pdo (yes | no) "no">

<!-- DES or AES -->
<!ELEMENT pproto (#PCDATA)>
<!ELEMENT ppassw (#PCDATA)>


<!-- request elements -->
<!ELEMENT request (oid*, non_rep?, max_rep?, result?)>
  <!ATTLIST request 
            type (set | get | getNext | getBulk | mib | inform ) "getNext">

<!ELEMENT oid (comment?, variable, value?)>
<!ELEMENT variable (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT result (#PCDATA)>

<!ELEMENT non_rep (#PCDATA)>
<!ELEMENT max_rep (#PCDATA)>

=== bartoszm/snmp123/resources/uk/co/westhawk/test/testIPv6.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE tests SYSTEM "./test.dtd">
<!--
-->
<tests>
    <test>
        <version no="3"/>
        <host>[fec0::28]</host>
        <port>161</port>
        <bind>[fec0::26]</bind>
        <socket_type type="STD"/>
        <usm>
            <username>privUser</username>
            <context>
                <id></id>
                <name></name>
            </context>
            <auth ado="yes">
                <aproto>MD5</aproto>
                <apassw>AuthPassword</apassw>
            </auth>
            <priv pdo="yes">
                <pproto>DES</pproto>
                <ppassw>PrivPassword</ppassw>
            </priv>
        </usm>
        <request type="getNext"> 
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
        </request>
        <request type="getNext"> 
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
        </request>
        <request type="getBulk"> 
            <oid>
                <comment>sysUpTime</comment>
                <variable>1.3.6.1.2.1.1.3</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <non_rep>1</non_rep>
            <max_rep>5</max_rep>
        </request>
        <request type="getBulk"> 
            <oid>
                <comment>sysUpTime</comment>
                <variable>1.3.6.1.2.1.1.3</variable>
            </oid>
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
            <non_rep>1</non_rep>
            <max_rep>50</max_rep>
        </request>
        <request type="get"> 
            <oid>
                <comment>sysDescr</comment>
                <variable>1.3.6.1.2.1.1.1.0</variable>
            </oid>
        </request>
        <request type="get"> 
            <oid>
                <comment>system</comment>
                <variable>1.3.6.1.2.1.1</variable>
            </oid>
        </request>
        <request type="set"> 
            <oid>
                <comment>sysLocation</comment>
                <variable>1.3.6.1.2.1.1.6.0</variable>
                <value>Westhawk Ltd</value>
            </oid>
        </request>
        <request type="mib"> 
            <oid>
                <comment>inetCidrRoute</comment>
                <variable> 1.3.6.1.2.1.4.24.7.1</variable>
            </oid>
        </request>
        <request type="inform"> 
            <oid>
                <comment>sysUpTime</comment>
                <variable>1.3.6.1.2.1.1.3</variable>
                <value>100</value>
            </oid>
            <oid>
                <comment>snmpTrapOID, warmStart</comment>
                <variable>1.3.6.1.6.3.1.1.4.1.0</variable>
                <value>1.3.6.1.6.3.1.1.5.2</value>
            </oid>
        </request>
    </test>
    <test>
        <version no="3"/>
        <host>[fec0::28]</host>
        <port>161</port>
        <bind>[fec0::26]</bind>
        <socket_type type="STD"/>
        <usm>
            <username>authSHAUser</username>
            <context>
                <id></id>
                <name></name>
            </context>
            <auth ado="yes">
                <aproto>SHA1</aproto>
                <apassw>AuthPassword</apassw>
