=== bartoszm/snmp123/resources/uk/co/westhawk/test/trap.dtd
<!-- /*
 * NAME
 *      $RCSfile: trap.dtd,v $
 * DESCRIPTION
 *      [given below]
 * DELTA
 *      $Revision: 1.4 $
 *      $Author: birgita $
 * CREATED
 *      $Date: 2009/03/05 12:59:50 $
 * COPYRIGHT
 *      Westhawk Ltd
 * TO DO
 *
 */ -->

<!-- all traps -->
<!ELEMENT traps (default, test*)>

<!-- default -->
<!ELEMENT default (port, socket_type)>

<!-- a trap test, listen for a certain host -->
<!ELEMENT test (version, host, port, bind, socket_type, (community | usm), result?)>

<!-- test elements -->
<!ELEMENT version EMPTY>
  <!ATTLIST version no (1 | 2c | 3) "1">
<!ELEMENT host (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT bind (#PCDATA)>
<!ELEMENT socket_type EMPTY>
  <!ATTLIST socket_type type (STD | NET | TCP) "STD">

<!ELEMENT community (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT result (#PCDATA)>


<!-- usm elements -->
<!ELEMENT usm (username, context, auth, priv?)>
<!ELEMENT username (#PCDATA)>
<!ELEMENT context (id, name)>
<!ELEMENT id (#PCDATA)> 
<!ELEMENT name (#PCDATA)> 

<!ELEMENT auth (aproto, apassw)?>
<!ATTLIST auth ado (yes | no) "no">

<!-- MD5 or SHA1 -->
<!ELEMENT aproto (#PCDATA)>
<!ELEMENT apassw (#PCDATA)> 

<!ELEMENT priv (pproto, ppassw?)>
<!ATTLIST priv pdo (yes | no) "no">

<!-- DES or AES -->
<!ELEMENT pproto (#PCDATA)>
<!ELEMENT ppassw (#PCDATA)>

=== bartoszm/snmp123/src/uk/co/westhawk/test/trapIPv6.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE traps SYSTEM "./trap.dtd">
<!--
-->
<traps>
    <default>
        <port>162</port>
        <bind>[fec0::26]</bind>
        <socket_type type="STD"/>
    </default>
    <test>
        <version no="1"/>
        <host>[fec0::28]</host>
        <port>161</port>
        <bind>[fec0::26]</bind>
        <socket_type type="STD"/>
        <community>public</community>
    </test>
    <test>
        <version no="2c"/>
        <host>[fec0::28]</host>
        <port>161</port>
        <bind>[fec0::26]</bind>
        <socket_type type="STD"/>
        <community>public</community>
    </test>
    <test>
        <version no="3"/>
        <host>[fec0::28]</host>
        <port>161</port>
        <bind>[fec0::26]</bind>
        <socket_type type="STD"/>
        <usm>
            <username>noAuthUser</username>
            <context>
                <id></id>
                <name>public</name>
            </context>
            <auth ado="no"></auth>
        </usm>
    </test>
</traps>

=== bartoszm/snmp123/resources/uk/co/westhawk/test/trapIPv4.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE traps SYSTEM "./trap.dtd">
<!--
-->
<traps>
    <default>
        <port>162</port>
        <bind>0.0.0.0</bind>
        <socket_type type="STD"/>
    </default>
    <test>
        <version no="1"/>
        <host>jessage</host>
        <port>161</port>
        <bind>0.0.0.0</bind>
        <socket_type type="STD"/>
        <community>public</community>
    </test>
    <test>
        <version no="2c"/>
        <host>jessage</host>
        <port>161</port>
        <bind>0.0.0.0</bind>
        <socket_type type="STD"/>
        <community>public</community>
    </test>
    <test>
        <version no="1"/>
        <host>selidor</host>
        <port>161</port>
        <bind>0.0.0.0</bind>
        <socket_type type="STD"/>
        <community>public</community>
    </test>
    <test>
        <version no="2c"/>
        <host>selidor</host>
        <port>161</port>
        <bind>0.0.0.0</bind>
        <socket_type type="STD"/>
        <community>public</community>
    </test>
    <test>
        <version no="1"/>
        <host>way</host>
        <port>161</port>
        <bind>0.0.0.0</bind>
        <socket_type type="STD"/>
        <community>public</community>
    </test>
    <test>
        <version no="2c"/>
        <host>way</host>
        <port>161</port>
        <bind>0.0.0.0</bind>
        <socket_type type="STD"/>
        <community>public</community>
    </test>
    <test>
        <version no="3"/>
        <host>way</host>
        <port>161</port>
        <bind>0.0.0.0</bind>
        <socket_type type="STD"/>
        <usm>
            <username>noAuthUser</username>
            <context>
                <id></id>
                <name>public</name>
            </context>
            <auth ado="no"></auth>
        </usm>
    </test>
    <!--
    <test>
        <version no="1"/>
        <host>host50</host>
        <port>161</port>
        <bind>0.0.0.0</bind>
        <socket_type type="STD"/>
        <community>public</community>
    </test>
    <test>
        <version no="2c"/>
        <host>host50</host>
        <port>161</port>
        <bind>0.0.0.0</bind>
        <socket_type type="STD"/>
        <community>public</community>
    </test>
    <test>
        <version no="3"/>
        <host>host50</host>
        <port>161</port>
        <bind>0.0.0.0</bind>
        <socket_type type="STD"/>
        <usm>
            <username>AuthUser</username>
            <context>
                <id>80000009030000115CF25651</id>
                <name></name>
            </context>
            <auth ado="yes">
                <aproto>MD5</aproto>
                <apassw>AuthPassword</apassw>
            </auth>
            <priv pdo="no"></priv>
        </usm>
    </test>
    -->
</traps>
